analysis:
    python 1-convert-classifications-to-easy-format.py
    python 2-summarize-classifications-by-subject.py
    python 3-crossmatch-stellar-and-planet-parameters.py
    python 4-identify-interesting-planets.py
